TWITTER_KEY: 'hljxf8HHtXHc7SSDa6G6bg'
TWITTER_SECRET: '4BxoQ0iYhB9Ydi3SwWbr9LSIBCjRyXE2BOvYrhSA'
OAUTH_TOKEN: '1426903309-Jvnsvox4kfGWsZr18Rc3nLumcosgJuj5JFL54AB'
OAUTH_TOKEN_SECRET: 'FUCMdA1jg4HhneMGUW29wjgCRp8Qa7o1zgElHIT74'
